### ISSUE TITLE
Character upside down after falling

### ISSUE THREAD

**Issue by codeeMadness** [Spacetime-Meta/spacetime-standard-kit#85]
After our Character falling, the character is up-side down.

https://user-images.githubusercontent.com/102911684/169102816-ac0d35a0-432f-487d-9b39-4d9e900c6f17.mp4

**Comment by codeeMadness** [comment]
Hi @Liquid-Blocks ,

Could you help to advise me how to fix this issue?

Regards,

**Comment by Liquid-Blocks** [comment]
Hi @codeeMadness,

After some experimenting, I found the issue seems to be in the `AvatarController.updatefacingDirection`, This because removing the following lines prevents the error:
![image](https://user-images.githubusercontent.com/46661277/169578786-25d34644-331e-4c63-a1e6-9316010b8c69.png)

Issue probably comes from a negative value appearing when the character falls under `Y = 0`, since lowering the terrain in spawn planet makes the avatar upside down by default.
![image](https://user-images.githubusercontent.com/46661277/169579769-a421aa22-cdf4-412a-a96d-02805c78546d.png)

**Comment by Liquid-Blocks** [comment]
This problem was solved in [this](https://github.com/Spacetime-Meta/spacetime-standard-kit/commit/6205041446c5f0f208423052a73bb3a6238f70c0) commit.
